### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by baimafeima** [afc163/fanyi#11]
Is this project still maintained? It hasn't seen a release in over three years. Could you make a new release here on GitHub or point me to any other terminal-based or GUI translation tools for Linux-based operating systems? Many thanks.

**Comment by colorwin** [comment]
[Try this](https://github.com/wufeifei/dict)

**Comment by afc163** [comment]
It is still maintained and will be published as npm package: http://npmjs.com/fanyi

Feel free to propose PR if there are bugs or you have new ideas.
