### ISSUE TITLE
Pronounce using Chinese voice

### ISSUE THREAD

**Issue by oluckyman** [afc163/fanyi#13]
`fy love` works as expected, the English voice said 'love'
But `fy 爱情` triggers the same English voice to pronounce symbols.

Would be awesome if it will detect that it’s the Chinese and call `say -v 'Ting-Ting' 爱情` internally

**Comment by afc163** [comment]
Supported in `fanyi@1.1.0`.

**Comment by oluckyman** [comment]
```
 Cannot find module 'is-chinese'
```

**Comment by afc163** [comment]
fanyi@1.1.1
