### ISSUE TITLE
请问为什么无法运行

### ISSUE THREAD

**Issue by HuangHongRui** [afc163/fanyi#16]
![image](https://user-images.githubusercontent.com/26321899/27419818-7107e70e-56e8-11e7-9264-7879404ef049.png)
![image](https://user-images.githubusercontent.com/26321899/27419849-8ee30e48-56e8-11e7-8164-27b96705e0db.png)

请问为什么无法运行

**Comment by HuangHongRui** [comment]
Thank you ~
This command_
sudo apt-get install festival festvox-kallpc16k

**Comment by colorwin** [comment]
应该不是这个工具的问题,
你看看`echo $PATH`的结果, 应该是你没把node包的目录加进去, 要看你是怎么安装node的
我的是'/rootpath/.nvm/versions/node/v7.7.1/bin'
