### ISSUE TITLE
I hope you can support simple mode, most of the time we just want to know the word means. example sentences are useless.

### ISSUE THREAD

**Issue by akamemoe** [afc163/fanyi#17]
today,I use putty to connect my server,the putty default window is small ,I can't see the translate result unless expanding the window full screen. all of the sentences is redundant。

**Comment by AmyDestiny** [comment]
BTW,the translate tool is very good and uesful. 

wish this tool better and better.

**Comment by youyiqin** [comment]
#### 同感，前辈，可以精简一点么？嘿嘿 :smile:

**Comment by Graywd** [comment]
@youyiqin  
在index.js 中，可以只保留自己想要的那个翻译源，其他注释掉。 
再细节就要加配置文件控制了。

**Comment by Songyu-Wang** [comment]
@afc163 please do PR regarding to this issue. Thank you (Mei shu ru fa da bu liao zhong wen)

**Comment by chenjiandongx** [comment]
#34 欢迎尝试 Python 版本的翻译工具

**Comment by Styx11** [comment]
这个可以尝试一下 https://github.com/Styx11/whats
它的设计初衷就是更简洁
