### ISSUE TITLE
感谢大佬，提一个建议

### ISSUE THREAD

**Issue by AHBICJ** [afc163/fanyi#29]
不是程序员，大佬考不考虑 加一个 Merriam-Webster 或者 en.oxforddictionaries.com for 英英

**Comment by jiaowoshabi** [comment]
@AHBICJ 可以试试这个Merriam-Webster 的app。https://github.com/jiaowoshabi/dict

**Comment by AHBICJ** [comment]
> @AHBICJ 可以试试这个Merriam-Webster 的app。https://github.com/jiaowoshabi/dict

好，谢谢

**Comment by Styx11** [comment]
这个可以尝试一下 https://github.com/Styx11/whats
它的设计初衷就是更简洁
