### ISSUE TITLE
Linux 只发音，没有翻译结果

### ISSUE THREAD

**Issue by codevvvv9** [afc163/fanyi#30]
已经升级到最新版了，目前只是发音，没有翻译的结果。
效果如图![](https://i.loli.net/2018/12/15/5c146454659b7.png)

**Comment by afc163** [comment]
https://github.com/afc163/fanyi#error-spawn-festival-enoent

试试这个，或者排查一下网络问题

**Comment by codevvvv9** [comment]
@afc163 好的，谢谢啦～，我卸载重装了然后已经好了

**Comment by xuwab** [comment]
@codevvvv9 你只做了卸载重装吗？一样的问题，我没解决[伤森]

**Comment by codevvvv9** [comment]
不行，现在又没用了，我已经放弃它了，卸载重装好多遍了，解决不了
