### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chenjiandongx** [afc163/fanyi#34]
感谢 @afc163 

这是一个很棒的项目，受这个项目启发，我实现了一个 Python 版的翻译工具 [chenjiandongx/fy](https://github.com/chenjiandongx/fy) 但新增了新特性 prompt shell 以及更加输出精简

**查单词**

![](https://user-images.githubusercontent.com/19553554/51759080-60407900-2102-11e9-8d8b-3de94c8a9c8a.png)

**英译中**

![](https://user-images.githubusercontent.com/19553554/51759141-849c5580-2102-11e9-9097-08f85bcb873f.png)

**中译英**

![](https://user-images.githubusercontent.com/19553554/51759144-8534ec00-2102-11e9-9cf7-349ad5f4954b.png)

**prompt shell**

![](https://user-images.githubusercontent.com/19553554/51759432-2d4ab500-2103-11e9-948d-45320fd90504.gif)

🙏🏻

**Comment by chenjiandongx** [comment]
**records shell** 也不错 开发者可以轻松查看查询历史

![](https://user-images.githubusercontent.com/19553554/51814828-2fc23000-22f8-11e9-9209-cc7ef15b40c6.gif)

**Comment by youyiqin** [comment]
真的很赞，不过感觉还是需要极简模式～
