### ISSUE TITLE
在查单词时，希望能提供这个单词的过去式、进行时、完成进行时，如果是名词，希望能提供复数表现形式

### ISSUE THREAD

**Issue by jjsty1e** [afc163/fanyi#43]

**Comment by Styx11** [comment]
可以试试 [whats](https://github.com/Styx11/whats) 翻译工具

whats 有简洁的输出结果，提供英文各时态翻译和中文的多音字翻译🙂

**Comment by Jaggle** [comment]
> 可以试试 [whats](https://github.com/Styx11/whats) 翻译工具
> 
> whats 有简洁的输出结果，提供英文各时态翻译和中文的多音字翻译🙂

赞，有空试试
