### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by youyiqin** [afc163/fanyi#57]
非常喜欢这个CLI，墙裂建议增加极简模式，有时候并不需要输出这么多信息。谢谢。

**Comment by Liuhongwei3** [comment]
> 非常喜欢这个CLI，墙裂建议增加极简模式，有时候并不需要输出这么多信息。谢谢。

确实，一般简单使用的话就返回一个接口的数据就行了（比如默认有道，查询不到再尝试另外的接口）

**Comment by youyiqin** [comment]
> > 非常喜欢这个CLI，墙裂建议增加极简模式，有时候并不需要输出这么多信息。谢谢。
> 
> 确实，一般简单使用的话就返回一个接口的数据就行了（比如默认有道，查询不到再尝试另外的接口）

实际上作者已经很久没管这个坑了,但是占了这个名.
