### ISSUE TITLE
自己怎么编译啊，最近发现用有道翻译不了了，终端也没有任何输出

### ISSUE THREAD

**Issue by neochne** [afc163/fanyi#82]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/7844207/219012118-456f4c75-5601-4c85-91ce-58a4ae10593d.png">

**Comment by neochne** [comment]
没事，不用解决了，我已经自己用 golang 实现了另一个终端翻译程序，感觉还是挺好用的

**Comment by bushnerd** [comment]
同样碰上这样的问题，有道的API是不给用了吗？
