### ISSUE TITLE
请问最新截图里颜色渐变特效是怎么实现的？

### ISSUE THREAD

**Issue by ghost** [afc163/fanyi#84]
是fanyi独有还是终端特效啊？是插件还是什么？有点漂亮，想整一个，谢谢！

**Comment by mmiris** [comment]
同问🐛

**Comment by Lan-ce-lot** [comment]
同问
看起来像是[warp](https://github.com/warpdotdev/Warp)的一个theme

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/53330071/227764339-19fa31bb-7652-47cc-8531-5180cfc67bf0.png">

输出字符颜色渐变不知道是如何实现的
